In [10]:
import numpy as np
first =np.arange(10000000)


NumPy-based algorithms are generally 10 to 100 times faster (or more)
than their pure Python counterparts and use significantly less memory.


In [11]:

%time for _ in range(10): my_arr2 =first*2

CPU times: total: 359 ms
Wall time: 359 ms


In [12]:
%time for _ in range(10): arr2 =[x*2 for x in first]

CPU times: total: 25.5 s
Wall time: 30.7 s


In [16]:
rng = np.random.default_rng(seed =12345 )
data =rng.standard_normal((2,3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [17]:
data + data

array([[-2.84765007,  2.52745692, -1.74132348],
       [-0.51834647, -0.15068661, -1.4817693 ]])

### 1 Check Data type


In [18]:
first.dtype 

dtype('int32')

### 2. Check shape of data

In [19]:
first.shape

(10000000,)

### 3. Creating a array

In [25]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [28]:
# two dimension array
d2_array = np.array([[1,2,3],[4,5,6]])
d2_array
# np.zeros(10)
# np.zeros((10,10))

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.empty((2,3,2))


array([[[1.41639743e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.33664410e+160]],

       [[4.22469314e-090, 6.11525887e+169],
        [5.41688705e-067, 4.25813682e+174],
        [6.48224659e+170, 4.93432906e+257]]])

In [31]:
#Arange is an array values version of built in function of python
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

### 4. Change data type
You can explicitly convert or cast an array from one dtype to another using
ndarray’s astype method

In [37]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [39]:
# convert int array to float array
float_arr =arr2.astype(np.float64)
float_arr.dtype

dtype('float64')

In [42]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

arr.astype(np.int32)


array([ 3, -1, -2,  0, 12, 10])

In [43]:
numeric_strings = np.array(['1.25', '-9.6', '42'],
dtype=np.string_)
numeric_strings.astype(float)


array([ 1.25, -9.6 , 42.  ])

### 5. Basic indexing & Slicing

In [45]:
arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[3:6]

array([3, 4, 5])

In [61]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

An important first distinction from Python’s built-in lists is that
array slices are views on the original array. This means that the data is not
copied, and any modifications to the view will be reflected in the source
array

In [63]:
arr_slice =arr[5:8]
arr_slice

array([12, 12, 12])

In [64]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [60]:
arr_slice[:] =64   
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### 2_D Array

In [102]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d.shape

(3, 3)

Thus, individual elements can be accessed recursively. But that is a bit too
much work, so you can pass a comma-separated list of indices to select
individual elements. So these are equivalent:


In [67]:
arr2d[0][2]

3

In [68]:
arr2d[0,2]

3

### 3_D Array

In [103]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],
[10, 11, 12]]])
print(arr3d)
print(arr3d.shape)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
old_values = arr3d[0].copy()
arr3d[0] = 42

In [75]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0]=  old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, arr3d[1, 0] gives you all of the values whose indices start
with (1, 0), forming a 1-dimensional array:

In [78]:
arr3d[1,0]

array([7, 8, 9])

In [80]:
x =arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [81]:
x[0]

array([7, 8, 9])

### 6 indexing with Slices

In [82]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [84]:
arr[3:7]

array([ 3,  4, 12, 12])

In [85]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [88]:
# I can select the second row but only the first two columns like
arr2d[1, :2]

array([4, 5])

In [90]:
# I can select the third column but only the first two rows
arr2d[:2, 2]

array([3, 6])

In [92]:
# Note that a colon by itself means to take the entire axis.
arr2d[:,:1 ]

array([[1],
       [4],
       [7]])

In [95]:
arr2d[:2, 1:] =0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [99]:
arr2d[2]
# arr2d[2, :]
# arr2d[2:, :]

array([7, 8, 9])

### Boolean Indexing

In [111]:
# boolean indexing, Let’s consider an example where we have some data in an array and an array of names with duplicates.
names = np.array(['Asif', 'Ali', 'Amir', 'Asif', 'Hamza','Zafar', 'Ibrahim'])
data =np.random.standard_normal((7,6))
names =='Asif'
#Suppose each name corresponds to a row in the data array and we wanted to select all the rows with corresponding name 'Bob'. Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized.
data[names=='Asif']

array([[ 1.52990174,  1.23057595,  1.44802948,  0.44843907,  1.63413035,
         0.44446778],
       [ 0.67060274,  1.45956075,  1.27435374,  0.22171698, -0.65659471,
         1.15106087]])

In [118]:
# data[names == 'Asif', 2:]
data[names =='Asif', 3]

array([0.44843907, 0.22171698])

In [131]:
data[data < 0] =0
data

array([[1.52990174, 1.23057595, 1.44802948, 0.44843907, 1.63413035,
        0.44446778],
       [0.35551468, 0.80698618, 0.        , 0.20581094, 0.        ,
        0.70650055],
       [0.        , 0.        , 0.        , 0.        , 1.47111092,
        1.0491726 ],
       [0.67060274, 1.45956075, 1.27435374, 0.22171698, 0.        ,
        1.15106087],
       [0.        , 0.        , 0.07330005, 0.74883434, 1.79951788,
        0.63865256],
       [0.82501967, 0.81602708, 0.34070403, 0.44904814, 0.        ,
        0.68270502],
       [0.        , 0.95502834, 0.16988826, 1.72025768, 0.        ,
        0.        ]])

In [136]:
data[names != 'Ali'] = 7

data

array([[7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.]])

### Fancy indexing

In [140]:
arr =np.empty((8,4))
for i  in range(8):
    arr[i] =i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [141]:
arr[[4,2,5,7]]
# arr[[-3, -5, -7]]


array([[4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])

### reshape() Method

In [142]:
np.arange(32).reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [144]:
arr[[3,4,5,2,7],[1,3,1,2,0]]

array([3., 4., 5., 2., 7.])

### Transposing and Swaping

In [145]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [148]:
#np.dot(arr.T , arr)
arr.T @ arr

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])

### Swap Axes

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [154]:
arr =np.arange(16).reshape((2, 2, 4))
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### Methods for Boolean Arrays

In [165]:
arr =np.random.standard_normal(100)

In [166]:
print((arr >0).sum())
print((arr<= 0).sum())

54
46


### Any(any value True in boolean Array)
### All(all value True in boolean Array)
There are two additional methods, any and all, useful especially for
boolean arrays. any tests whether one or more values in an array is True,
while all checks if every value is True:


In [172]:
# Any 
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())

True
False


In [174]:
## Sort
arr.sort()
arr

array([-2.41798062, -1.90708811, -1.84100756, -1.49636023, -1.4222728 ,
       -1.35629498, -1.34338539, -1.13074397, -1.09373493, -1.03969274,
       -0.96846906, -0.91475703, -0.90746297, -0.90236829, -0.85970738,
       -0.78885173, -0.78219999, -0.76500304, -0.71916505, -0.6967962 ,
       -0.69455037, -0.68077354, -0.66045584, -0.65542106, -0.5627163 ,
       -0.51038092, -0.47571165, -0.46163563, -0.44732047, -0.42459828,
       -0.40923983, -0.40275896, -0.397837  , -0.39011378, -0.38513792,
       -0.3262677 , -0.26477418, -0.25277095, -0.23722167, -0.23709264,
       -0.22011817, -0.1600834 , -0.13147874, -0.12489628, -0.10584321,
       -0.06018128,  0.04582906,  0.06002097,  0.07522201,  0.08621122,
        0.12665559,  0.14265521,  0.18318008,  0.18348155,  0.24246736,
        0.25435669,  0.26185368,  0.28022609,  0.3396895 ,  0.3588051 ,
        0.39433922,  0.41068496,  0.43442953,  0.45196608,  0.52084297,
        0.5411995 ,  0.54428768,  0.58352146,  0.5963763 ,  0.63

### Unique and Other Set Logic

In [176]:
names = np.array(['Asif', 'Ali', 'Amir', 'Asif', 'Asif','Ali', 'Ibrahim'])
np.unique(names)

array(['Ali', 'Amir', 'Asif', 'Ibrahim'], dtype='<U7')

In [181]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [ ]:
np.intersect1d()